### ISSUE TITLE
Regarding the number of results returned for WebSearch

### ISSUE THREAD

**Issue by coolashish** [tristantao/py-ms-cognitive#10] opened 2017-01-20 09:37 UTC
PyMsCognitiveWebSearch returns 50 results each time, irrespective of value of limit variable specified. 

In the class PyMsCognitiveWebSearch, under _search function, the payload dictionary has count initialized to 50. It should instead be initialized to limit.

This will fix the bug.

**Comment by tristantao** [comment] 2017-01-23 18:18
I see the issue. I think it's the result of ambiguity on my part; the limit param was intended to create an upper limit for search_all() function. I.e. calling search_all(limit=130) will return roughly 130 results.

I'm considering revamping search_all so that it takes in a __*quota*__ param and changing the limit in search(limit=45) to actually return 45 results.

**Comment by tristantao** [comment] 2017-01-23 21:49
This will be fixed up and clarified via #13

**Closed as completed by tristantao** 2017-01-23 21:49 UTC
Labels: enhancement
